def cornthians():
    print('''SALVE O CORINTHIANS O CAMPEÃO DOS CAMPEÕES
ETERNAMENTE DENTRO DOS NOSSOS CORAÇÕES
SALVE O CORINTHIANS DE TRADIÇÕES E GLÓRIAS MIL
TÚ ÉS ORGULHO DOS DESPORTISTAS DO BRASIL

TEU PASSADO É UMA BANDEIRA
TEU PRESENTE É UMA LIÇÃO
FIGURAIS DENTRE OS PRIMEIROS
DO NOSSO ESPORTE BRETÃO

CORINTHIANS GRANDE SEMPRE ALTANEIRO
ÉS DO BRASIL O CLUBE MAIS BRASILEIRO''')

cornthians()
